### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by rakhi99** [shawnspeak/stream-net#22]
Hi,

I am using https://github.com/shawnspeak/stream-net c# library 
How can I get single users aggregated feed using this library?

How to get likes and comments of a single activity?
If I use this library's GetActivities function it returns like and comment within feed, but what I need is likes and comments on that activity.

**Comment by hannesvdvreken** [comment]
Hi,

We suggest (for all applications that are using Stream) to store everything you need on your side, and to send Stream only what it needs to create the feeds.

So in your case: I'd store all activities, all likes, all comments. And when someone created a comment, add an activity with verb "comment" to a Stream feed.

Like so you can ask your database for all comments, or all likes, for a single activity.

Does that help?

**Comment by shawnspeak** [comment]
Did you get this figured out @rakhi99 ? @hannesvdvreken suggestion is exactly how I've implemented this previously.

**Comment by reddy6ue** [comment]
I was planning on creating my reference object with foreign id in my database, and then sending the request to stream, and using the webhook to import the activity metadata back into the feed in my database. 

Is this the right course of action?

**Comment by shawnspeak** [comment]
@reddy6ue What metadata are you thinking of adding back after the webhook callback?

In general, when I create a reference object in my database it is a complete "record". Once I'm certain it's been persisted, then I create the Stream activities that reference it. I only use the webhook to invalidate caches and update UI when needed.

**Comment by reddy6ue** [comment]
I am using the update json in the webhook body to enrich my feed  items and update the interaction metadata like likes, comments, shares, etc. in my feeditems. On the stream website, this is given as a sample webhook body. 

```
[
        {
          "deleted":[],
          "new":[{"actor":"1","verb":"tweet","object":"1","target":null,"time":"2014-12-15T17:20:37.258","foreign_id":null,"id":"af781804-847e-11e4-8080-80012fb97b9e","tweet":"Hello world"}],
          "published_at":"2014-12-15T17:20:37.263518+00:00",
          "feed":"user:2",
          "app_id": "123"
        },
        {
          "deleted":["38f81366-847f-11e4-9c94-0cc47a024be0"],
          "new":[],
          "published_at":"2014-12-15T17:20:37.263518+00:00",
          "feed":"timeline:1",
          "app_id": "123"
        }
      ]

```

I think we need a data structure to accommodate this json format in this library. Maybe even add a few WebhookUtils for stream processing of the json data and the like.

**Comment by reddy6ue** [comment]
I'll see if I can generate a pull request with whatever I come up with.

**Comment by mian-rehan-nasir** [comment]
hello
i am using stream-net in my .net mvc web application to handle feeds/social media interaction.

I have been able to create feeds and add activities to it as well as show these activities to the 'followers' of that particular feed.
When it comes to capturing 'Like' data, i am confused.

Mr. Hannes comment (2.Nov.2017) suggest that the 'Like' data (eg: User 998 LIKED post zxc0980) should be saved in the local application's database. However after reading 'Social Music App tutorial' on getStream.io website, i get a feel that 'LIKE' action can be added to GetStream as well.

I am bit confused and wonder what should be the right approach. If LIKEs and COMMENTs are to be stored in the local database then adding these to ACTIVITY should be part of 'Enriching the data'. That means, the Activity info is retreived from GetStream API and then COMMENTS and LIKES to be added to it from local database. Finally show this to user?

any hint will be much appreciated.

**Comment by shawnspeak** [comment]
There are a number of ways to accomplish this situation, but I prefer to treat Stream as a means to inform users of activities instead of treating it as a data store. My "LIKE" process would goes something like this:

1. User (`user:345`) clicks LIKE a post (`post:456`)
2. Save the LIKE to my datastore with a unique id (`like:123`)
3. Once I'm satisified that LIKE is stored (transaction/update log/trigger/etc), then I'd add an activity to Stream as follows:
`
var activity = new Activity("user:345", "likes", "post:456") 
{
	ForeignId = "like:123"
}
`
4. Then as I retrieve the activities, I'd enrich them from my datastores prior returning it on a page/api call/etc. (Assuming I'm only enriching LIKEs) When returning multiple activities, I'd call Stream to get a block of activities, then loop through them and collect all of the foreign id's into a list. Then make a single query to my datastore to get all of the LIKEs in question. Finally, merge the activity and LIKE together in whatever your final presentation needs to be.

I use this pattern throughout all of my Stream interactions and it's worked out well for me.

**Comment by reddy6ue** [comment]
Close this if the user is unresponsive?
