### ISSUE TITLE
AddActivity error :The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by mennolaan** [shawnspeak/stream-net#24]
I recently transfered all the calls with stream-net to Azure Functions (Queue triggers). With version 1.3.2 everything worked like a charm, however when updating the nuget package to 2.0.1 in order to use the new api points I get this message:

**The request was aborted: Could not create SSL/TLS secure channel.**
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)

The funny thing is, if I run a small project locally to use AddActivity, everything goes well.

If I use **ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;** just before  I call  **StreamClient GetStreamsClient = new StreamClient("xxx","xxx");** it does work.

 So a heads up to developers running into this issue with azure functions & stream-net.

Ps great stuff Shawn!

**Comment by shawnspeak** [comment]
Thanks for the report @mennolaan .

What .Net framework are you targeting with your Azure function?

**Comment by mennolaan** [comment]
At the moment I'm targetting 4.6.1. 

Im okay with closing this issue if you would like to do that. If somebody googles stream-net & ssl/tls, they will find the solution above. The fix is not on your end, its Azure as far as I can see.

**Comment by shawnspeak** [comment]
Ok. The workaround you provided is exactly how I'd solve this issue. The consequences of that code however is that it effects the SSL negotiation of every https request within the entire AppDomain. Let me do some more research and see what I can come up.

**Comment by JelteF** [comment]
Employee of stream here. Thanks for maintaining this client. Another of our customers had a similar error (also on .net 4.6.1) and solved it by using:
```
System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
```

Since recently we don't support TLS 1.0 anymore at all. Also not on the old API endpoints, so I think more people will be running into this problem. 

I'm not familiar with .NET, but I would assume you could also do the following to only add support for new protocols:
```
System.Net.ServicePointManager.SecurityProtocol = System.Net.ServicePointManager.SecurityProtocol | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
```

**Comment by shawnspeak** [comment]
I wish it were that easy. The various .Net versions all have different defaults and in fact the latest .Net Core no longer uses the ServicePointManager to control Security Protocol settings. As more folks migrate to .Net Core, this will no longer be an issue as the SSL negotiation issues have been, for the most part, resolved.

In the meantime, if I add that line of code to the library it effects every SSL connection within the AppDomain... think process-wide. I hate it when libraries make global changes which is why I've been reluctant to change the setting for the .Net 4.6.1 version.

**Comment by reddy6ue** [comment]
@shawnspeak Maybe this issue should also be closed?
