### ISSUE TITLE
Activities for posting messages TO

### ISSUE THREAD

**Issue by rosenbergp** [shawnspeak/stream-net#6]
Hi, Shawn,

I hope you don't mind, since I am new to social feeds and following stuff. I have some more questions.

Can you show me a syntax example on how to do an activity, to post a message TO someone else?

Similar to the below code, but using your stream-net client:

// specifying additional feeds to push the activity to using the to param
// especially usefull for notification style feeds
to = ['user:2', 'user:3'];
activity = {'to': to, 'actor': 1, 'verb': 'tweet', 'object': 1, 'foreign_id': 'tweet:1'};

The reason I am asking, is we want to have user 1 go to user 2's feed and post a message.
When that happens we want user 1's feed to receive the post, so all user 1's followers see it and we want it to show up in user 2's feed and have all user 2's followers see it.

Can we accomplish that with the TO functionality?

**Comment by shawnspeak** [comment]
Patrick,

There are a number of ways to accomplish what you are looking to do and I am by no means an expert when it comes to using Stream. I'll take a stab at answering your question, but you may want to contact Stream and see what they have to say.

In my Stream projects, every user has a `user` feed in which every action of that user get's added. I also create an `aggregate` feed for each user which follows that user's `user` feed. When a user follows another, I have the `aggregate` feed of the follower follow the `user` of the one being followed. When my users log in, they see their `aggregate` feed on the screen as it represents all of the things the user follows which includes the activities that they perform themselves.

So in your case, User 1 (and every other user) would have their own `user` feed and an `aggregate` feed which follows the `user` feed:

```
var user1 = client.Feed("user", "1");
var agg1 = client.Feed("aggregate","1");
await agg1.FollowFeed(user1);
// repeat for every user
```

Then lets say that User 3 follows User 1. So User 3's `aggregate`, follows User 1's `user` because when User 3 logs in, they are looking at the their aggregate and this will display the activity that User 1 is performing:

```
var user1 = client.Feed("user", "1");
var agg3 = client.Feed("aggregate","3");
await agg3.FollowFeed(user1);
```

Then User 1 posts to User 2. Since User 1 is doing the posting, you add the activity to User 1's `user` feed. Every user that follows User 1, including User 3, will see that User 1 posted the message. However, User 2 may not be following User 1. To ensure that User 2 see's the fact that User 1 posted a message, you use the `To` property to copy the activity to the `aggregate` feed of User 2.

```
var user1Posted = new Activity("user:1","posted","message:1234");
// add extra data to activity
user1Posted.To = new String[] { "aggregate:2" }.ToList();
await user1.AddActivity(user1Posted);
```

Now when all the users log in and look at their `aggregate` feeds, they see the fact that User 1 posted a message to User 2.
- User 1, because it was added to their own `user` feed
- User 2, because the activity was copied to their `aggregate` feed
- User 3, because their `aggregate` feed follows User 1's `user` feed

That all make sense?
