### ISSUE TITLE
test that JSON serialization for custom data is correctly serialized

### ISSUE THREAD

**Issue by tbarbugli** [shawnspeak/stream-net#9]
one user reported an issue related to how activities are serialized to JSON. It seems like in their case that a variable with type Double (1) gets serialized to JSON as the string "1".

**Comment by shawnspeak** [comment]
Yes. All variables get serialized to strings regardless of type. Should it be different?

**Comment by tbarbugli** [comment]
that breaks custom ranking because it becomes impossible for the the user to send floats or integers. 
I am not really familiar with C# but looking at the code it seems this should be very easy to fix:

in https://github.com/shawnspeak/stream-net/blob/master/src/stream-net/Activity.cs#L107 we only need to return the serialized objects instead of its string representation

```
return JsonConvert.SerializeObject(obj);
```

**Comment by shawnspeak** [comment]
It's an easy change for primitives, but when you pass complex objects into that method then things get complicated. Since the JSON being retrieved with the activity doesn't have a C# type assigned to the complex object, the initial deserialization of the activity fails. Treating everything as a string keeps it simple and delays the type specific deserialization to the point at which it's needed.. where we are getting the complex type passed into the generic method.

Let me think through it a bit and see if I can come up with a better solution.

**Comment by tbarbugli** [comment]
I think fail to serialize anything else then primitives is already an improvement. at least the user is not sending the string representation of an object which will be probably not that useful when read back ;)

**Comment by shawnspeak** [comment]
I (wrongly) assumed that if a user was creating activities with the .Net library.. then they would be most likely retrieving those activities with the library. In which case, there is no issue. In my use cases, I've never added anything other than strings as custom data and so didn't run across this. Regardless, the library should be storing proper JSON.

**Comment by shawnspeak** [comment]
Tommaso, I've come up with a solution that will properly serialize primitives and complex objects and should also handle any previous activities that were created with string representations. Should have it pushed shortly.

**Comment by shawnspeak** [comment]
@tbarbugli, The nuget package has been updated.
